name: Setup node.js
description: Set up your GitHub Actions workflow with a specific version of node.js
inputs:
  node-version:
    description: The node.js version to use
    required: false
    default: "22.14.0"
runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
    - name: Enable Corepack
      shell: bash
      run: |
        mkdir -p "$HOME/.local/bin"
        corepack enable --install-directory "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        corepack prepare yarn@4.10.0 --activate
