version: 2.1

orbs:
  node: circleci/node@5.3.0
  auto: artsy/auto@2.2.0
  macos: circleci/macos@2.5.4

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

executors:
  node:
    docker:
      - image: cimg/node:20.9.0

jobs:

workflows:
  build-deploy:
    jobs:
      - node/test:
          name: test
          version: "20.9.0"
          pkg-manager: yarn
          run-command: "test"

      - node/run:
          name: type-check
          version: "20.9.0"
          pkg-manager: yarn
          yarn-run: "type-check"

      - auto/publish-canary:
          context: npm-deploy
          node-version: "20.9.0"
          filters:
            branches:
              ignore: main
          requires:
            - test
            - type-check

      - auto/publish:
          context: npm-deploy
          node-version: "20.9.0"
          filters:
            branches:
              only: main
          requires:
            - test
            - type-check
