version: 2.1

orbs:
  node: circleci/node@5.2.0
  auto: artsy/auto@2.1.0
  macos: circleci/macos@2.4.1

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

executor:
  name: node/default
  tag: "20.9.0"

jobs:
  build-ios:
    macos:
      xcode: "15.1.0"
    steps:
      - checkout
      - run:
          name: Check if iOS directory or Podfile.lock changed
          command: |
            if ! git diff --name-only origin/main... | grep -E 'ios/|Podfile.lock'; then
              echo "No changes in iOS directory or Podfile.lock. Skipping build."
              circleci step halt
            fi
      - run: yarn install:all
      - run: yarn ios

  build-android:
    docker:
      - image: cimg/android:2023.12.1-node
    steps:
      - checkout
      - run:
          name: Check for relevant changes in Android files
          command: |
            if ! git diff --name-only origin/main... | grep -E 'android/|.*\.gradle$|.*\.java$|.*\.xml$'; then
              echo "No relevant changes detected in Android files. Skipping Android build."
              circleci step halt
            fi
      - run:
          name: Install ninja
          command: sudo apt-get install ninja-build
      - run: yarn install
      - run:
          name: Build Android App
          command: cd android && ./gradlew assembleDebug

workflows:
  build-deploy:
    jobs:
      - node/test:
          name: test
          version: "20.9.0"
          pkg-manager: yarn
          run-command: "test"

      - node/run:
          name: type-check
          version: "20.9.0"
          pkg-manager: yarn
          yarn-run: "type-check"

      - build-ios:
          requires:
            - test
            - type-check

      - build-android:
          requires:
            - test
            - type-check

      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore: main
          requires:
            - test
            - type-check

      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: main
          requires:
            - test
            - type-check
