version: 2.1

orbs:
  node: circleci/node@5.2.0
  auto: artsy/auto@2.1.0
  macos: circleci/macos@2.4.1
  test-auto:
    version: 2.1
    description: "Publish NPM packages and canary deployments with Intuit's Auto"
    orbs:
      yarn: artsy/yarn@5.1.3
      auto: auto/release@0.2.3
      utils: artsy/orb-tools@0.5.0
    executors:
      node:
        parameters:
          node-version:
            type: string
            default: "14.18.1"
        docker:
          - image: cimg/node:<< parameters.node-version >>
    jobs:
      publish:
        parameters:
          node-version:
            type: string
            default: "14.18.1"
          version:
            type: string
            default: v10.36.5
          args:
            type: string
            default: ""
        executor:
          name: node
          node-version: << parameters.node-version >>
        environment:
          AUTO_VERSION: << parameters.version >>
        steps:
          - yarn/pre-release
          - auto/shipit:
              arguments: << parameters.args >>
      publish-canary:
        parameters:
          node-version:
            type: string
            default: "14.18.1"
          version:
            type: string
            default: v10.36.5
          args:
            type: string
            default: ""
        executor:
          name: node
          node-version: << parameters.node-version >>
        environment:
          AUTO_VERSION: << parameters.version >>
        steps:
          - utils/skip-if-fork-or-not-pr:
              pr-skip-message: "Skipping, only deploys canaries on PR builds"
              fork-skip-message: "Skipping, can't deploy canaries from a fork"
          - yarn/pre-release
          - auto/canary:
              arguments: << parameters.args >>

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

executors:
  node:
    docker:
      - image: cimg/node:20.9.0

jobs:
  build-ios:
    macos:
      xcode: "15.1.0"
    steps:
      - checkout
      - run:
          name: Check if iOS directory or Podfile.lock changed
          command: |
            if ! git diff --name-only origin/main... | grep -E 'ios/|Podfile.lock'; then
              echo "No changes in iOS directory or Podfile.lock. Skipping build."
              circleci step halt
            fi
      - run: yarn install:all
      - run: yarn ios

  build-android:
    docker:
      - image: cimg/android:2023.12.1-node
    steps:
      - checkout
      - run:
          name: Check for relevant changes in Android files
          command: |
            if ! git diff --name-only origin/main... | grep -E 'android/|.*\.gradle$|.*\.java$|.*\.xml$'; then
              echo "No relevant changes detected in Android files. Skipping Android build."
              circleci step halt
            fi
      - run:
          name: Install ninja
          command: sudo apt-get install ninja-build
      - run: yarn install
      - run:
          name: Build Android App
          command: cd android && ./gradlew assembleDebug

workflows:
  build-deploy:
    jobs:
      - node/test:
          name: test
          version: "20.9.0"
          pkg-manager: yarn
          run-command: "test"

      - node/run:
          name: type-check
          version: "20.9.0"
          pkg-manager: yarn
          yarn-run: "type-check"

      - build-ios:
          requires:
            - test
            - type-check

      - build-android:
          requires:
            - test
            - type-check

      - test-auto/publish-canary:
          context: npm-deploy
          node-version: "20.9.0"
          filters:
            branches:
              ignore: main
          requires:
            - test
            - type-check

      - test-auto/publish:
          context: npm-deploy
          node-version: "20.9.0"
          filters:
            branches:
              only: main
          requires:
            - test
            - type-check
