version: 2.1

orbs:
  node: circleci/node@5.0.2
  auto: artsy/auto@2.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build-lib:clean
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    executor: node/default
    steps:
      - run: yarn release

  publish-canary:
    executor: node/default
    steps:
      - run: yarn release:canary

workflows:
  publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only: main
          requires:
            - build

  publish-canary:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - publish-canary:
          filters:
            branches:
              ignore: main
          requires:
            - build
