version: 2.1

orbs:
  node: circleci/node@6.3.0
  auto: artsy/auto@2.3.0
  macos: circleci/macos@2.5.4

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

executor:
  name: node/default
  tag: << pipeline.parameters.node_version >>

jobs:
  build-ios:
    macos:
      xcode: 16.2
      resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: Check if iOS directory or Podfile.lock changed
          command: |
            if ! git diff --name-only origin/main... | grep -E 'Example/ios/|Example/.*Podfile.lock'; then
              echo "No changes in iOS directory or Podfile.lock. Skipping build."
              circleci step halt
            fi
      - run: yarn install:all
      - run: yarn ios:prebuild
      - run:
          name: Build iOS App
          command: cd Example/ios && xcodebuild build -workspace PaletteMobile.xcworkspace -scheme PaletteMobile -destination 'platform=iOS Simulator,name=iPhone 15'

  build-android:
    docker:
      - image: cimg/android:2023.12.1-node
    steps:
      - checkout
      - run:
          name: Check for relevant changes in Android files
          command: |
            if ! git diff --name-only origin/main... | grep -E 'Example/android/|.*\.gradle$|.*\.java$|.*\.xml$'; then
              echo "No relevant changes detected in Android files. Skipping Android build."
              circleci step halt
            fi
      - run:
          name: Install ninja
          command: sudo apt-get install ninja-build
      - run: yarn install
      - run: yarn android:prebuild
      - run:
          name: Build Android App
          command: cd Example/android && ./gradlew assembleDebug

parameters:
  node_version:
    type: string
    default: "22.0.0"

workflows:
  build-deploy:
    jobs:
      - node/test:
          name: test
          version: << pipeline.parameters.node_version >>
          pkg-manager: yarn-berry
          run-command: "test"

      - node/run:
          name: type-check
          version: << pipeline.parameters.node_version >>
          pkg-manager: yarn-berry
          yarn-run: "type-check"

      - build-ios:
          requires:
            - test
            - type-check

      - build-android:
          requires:
            - test
            - type-check

      - auto/publish-canary:
          context: npm-deploy
          node-version: << pipeline.parameters.node_version >>
          filters:
            branches:
              ignore: main
          requires:
            - test
            - type-check

      - auto/publish:
          context: npm-deploy
          node-version: << pipeline.parameters.node_version >>
          filters:
            branches:
              only: main
          requires:
            - test
            - type-check
