version: 2.1

orbs:
  node: circleci/node@7.2.0
  auto: artsy/auto@2.2.0
  macos: circleci/macos@2.5.4

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

executors:
  node:
    docker:
      - image: cimg/node:22.0.0

jobs:
  build-ios:
    macos:
      xcode: 16.2
      resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: Check if iOS directory or Podfile.lock changed
          command: |
            if ! git diff --name-only origin/main... | grep -E 'ios/|Podfile.lock'; then
              echo "No changes in iOS directory or Podfile.lock. Skipping build."
              circleci step halt
            fi
      - run: yarn install:all
      - run: yarn prepublishOnly

  build-android:
    docker:
      - image: cimg/android:2023.12.1-node
    steps:
      - checkout
      - run:
          name: Check for relevant changes in Android files
          command: |
            if ! git diff --name-only origin/main... | grep -E 'android/|.*\.gradle$|.*\.java$|.*\.xml$'; then
              echo "No relevant changes detected in Android files. Skipping Android build."
              circleci step halt
            fi
      - run:
          name: Install ninja
          command: sudo apt-get install ninja-build
      - run: yarn install
      - run:
          name: Build Android App
          command: yarn prepublishOnly

parameters:
  node_version:
    type: string
    default: "22.0.0"

workflows:
  build-deploy:
    jobs:
      - node/test:
          name: test
          version: << pipeline.parameters.node_version >>
          pkg-manager: yarn
          run-command: "test"

      - node/run:
          name: type-check
          version: << pipeline.parameters.node_version >>
          pkg-manager: yarn
          yarn-run: "type-check"

      - build-ios:
          requires:
            - test
            - type-check

      - build-android:
          requires:
            - test
            - type-check

      - auto/publish-canary:
          context: npm-deploy
          node-version: << pipeline.parameters.node_version >>
          filters:
            branches:
              ignore: main
          requires:
            - test
            - type-check

      - auto/publish:
          context: npm-deploy
          node-version: << pipeline.parameters.node_version >>
          filters:
            branches:
              only: main
          requires:
            - test
            - type-check
