version: 2.1

orbs:
  auto: artsy/auto@2.1.0

executor:
  name: node/default

jobs:
  build:
    steps:
      - run: yarn build-lib:clean

  publish:
    steps:
      - run: yarn release

  publish-canary:
    steps:
      - run: yarn release:canary

workflows:
  publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only: main
          requires:
            - build

  publish-canary:
    jobs:
      - build
      - publish-canary:
          filters:
            branches:
              ignore: main
          requires:
            - build
