# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :beta do
    increment_build_number(xcodeproj: "ios/PaletteMobile.xcodeproj")
    build_app(workspace: "ios/PaletteMobile.xcworkspace", scheme: "PaletteMobile", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight # you need `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in the env with an app-specific password
  end
end
