#!/usr/bin/env bash
set -euxo pipefail


# Get fonts from eigen s3 bucket
aws s3 cp s3://artsy-citadel/eigen/fonts.tar.gz ./fonts.tar.gz

# Extract fonts
mkdir -p ./fonts
tar -xvzf fonts.tar.gz -C ./fonts
